name: Playwright Tests

on:
  push:
    branches: [ main ]
  pull_request:
  workflow_dispatch:

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'npm'

      - name: Install deps
        run: npm ci

      - name: Install Playwright browsers
        run: npx playwright install --with-deps

      - name: Run tests
        run: npm test
        env:
          STANDARD_PASSWORD: ${{ secrets.STANDARD_PASSWORD }}

      - name: Upload HTML report
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: playwright-report_${{ github.run_number }}
          path: playwright-report
          retention-days: 7

      - name: Upload failure artifacts (traces/screenshots/videos)
        if: failure()
        uses: actions/upload-artifact@v4
        with:
          name: test-results_${{ github.run_number }}
          path: test-results/**
          retention-days: 7
